### ISSUE TITLE
Not localized on macOS (JVM)

### ISSUE THREAD

**Issue by StefanOltmann** [vinceglb/FileKit#42]
Thanks for making this lib!
I like its API very much.

I noticed that on macOS (JVM) the FilePicker as well as the DirectoryPicker are not localized. They are always presented in English. On Windows the pickers are presented in the systems default language.

This is the same problem I currently encounter with [compose-multiplatform-file-picker](https://github.com/Wavesonics/compose-multiplatform-file-picker/issues/141).

**Comment by vinceglb** [comment]
Thank you @StefanOltmann!

I was able to localize the picker by modifying the Info.plist of the project and adding the "Localizations" key and the different languages I wanted to support in the app:

![CleanShot 2024-07-06 at 15 15 09](https://github.com/vinceglb/FileKit/assets/24540801/f23da451-b63d-425c-9acf-160d13b28d6f)

After that, the picker is automatically localized if the language is supported in the Info.plist:

![CleanShot 2024-07-06 at 15 16 58](https://github.com/vinceglb/FileKit/assets/24540801/e071e969-5489-41a6-97e9-e2b37ba8417b)

If you don't have access to the Info.plist because you're using Compose Multiplatform, you can use [this documentation](https://github.com/JetBrains/compose-multiplatform/tree/f01f195f2a208af36af7a6779798ed85acae4f58/tutorials/Native_distributions_and_local_execution#customizing-infoplist-on-macos) to modify the Info.plist like you want.

Does this solve your issue?

**Comment by StefanOltmann** [comment]
Thank you. I will look into that next week. :)
