### ISSUE TITLE
Option to use the better file picker on Windows

### ISSUE THREAD

**Issue by StefanOltmann** [vinceglb/FileKit#43]
I find the picker shown on Windows rather unusual. I know, it's the systems picker for that, but most apps I know present another picker for directories.

It looks like the file picker, but it lets users only choose directories and displays users bookmarks on the left.

Please add an option to use this picker instead.

See also https://github.com/Wavesonics/compose-multiplatform-file-picker/issues/83#issuecomment-1839268951

**Comment by tofu-guy** [comment]
Would love to see this, I've tried so many different file pickers for the JVM, and basically all of them default to the old, and quite frankly, ugly file pickers.

The only directory picker I've used that used the more modern looking one is that one that's bundled with JavaFX, but I'd rather not bundle all of JavaFX just to be able to use a better looking directory picker..

**Comment by vinceglb** [comment]
@StefanOltmann, I have good news ✨

FileKit was using an old Windows API to display dialogs.

By looking into the old thread, there was a mention about `NativeFileDialog`. By searching on internet, I found this [C library](https://github.com/mlabbe/nativefiledialog) doing exactly what we wanted to do. In the code, I found that they use the IFileDialog Windows API. IFileDialog [is recommended by Microsoft](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shbrowseforfoldera#remarks) to display dialogs since Windows Vista.

By luck, it exists [this repository](https://github.com/dbwiddis/IFileDialogImp) binding IFileDialog API to Java using JNA. 

I adapted the code to Kotlin and reproduced the behavior from the C library.

It enables FileKit to use a uniformed and up-to-date Windows API with latest UI 🎉

You can visit this PR to have more info and some examples: https://github.com/vinceglb/FileKit/pull/88

**Comment by StefanOltmann** [comment]
@vinceglb Thank you so much! This is fantastic news!
