### ISSUE TITLE
Problems when creating Release Distributable for Desktop with Proguard

### ISSUE THREAD

**Issue by PMARZV** [vinceglb/FileKit#56]
When creating an optimized and ofuscated release distributable in Compose Desktop, there seems to be problems with JNA. Could it be possible if you created a proguard rules file for the library? 
![Captura de pantalla 2024-07-05 174346](https://github.com/vinceglb/FileKit/assets/100836358/508b17b7-94a3-42e8-ad7c-6c7674b22275)
![Captura de pantalla 2024-07-05 173458](https://github.com/vinceglb/FileKit/assets/100836358/91005b4f-aa02-4d98-bb04-cce7d5f8accd)

**Comment by vinceglb** [comment]
Thanks for reporting this!

I'm trying to reproduce the crash but for now I didn't succeed. Here are the steps I tried:
- On Windows 11
- By reading [the documentation](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Native_distributions_and_local_execution/README.md#minification--obfuscation), I tried to activate Obfuscation because it is disable by default and ProGuard's optimizations are enabled by default
- I modified the sample-compose build.gradle with these lines

```kotlin
compose.desktop {
    application {
        mainClass = "MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "io.github.vinceglb.sample.compose"
            packageVersion = "1.0.0"
        }

        // New here
        buildTypes.release.proguard {
            obfuscate.set(true)
        }
    }
}
```
- I build the sample using `./gradew samples:sample-compose:composeApp:packageMsi`
- I installed the application on my windows

But the app worked like expected, it didn't crash. Am I missing something?

Are you able to reproduce the crash using the sample-compose?

**Comment by PMARZV** [comment]
Packaging with Msi doesnt crash (`proguardReleaseJars` gradle task doesnt seem to be called when `packageMsi` is ran, so the package isnt being optimized or ofuscated, i guess). Thats why i said run the task `createReleaseDistributable` (which is calling `proguardReleaseJars` gradle task and crashing the sample-compose for me at least)

**Comment by vinceglb** [comment]
I'm still trying to reproduce the crash. Without creating a proguard file, I can even build sample-compose using `createReleaseDistributable` on Windows and macOS due to proguard warnings.

On macOS, I manage to build and launch correctly the sample-compose by creating this proguard file:

```
-dontwarn kotlinx.datetime.**
-dontwarn org.slf4j.**
-keep class org.slf4j.**{ *; }
-keep class com.sun.jna.* { *; }
-keep class * implements com.sun.jna.* { *; }
```

But on Windows, I'm faced with more 100 000 proguard warnings. I tried the same proguard file and experiment with it but I failed to build the sample-compose app.

Are you using a proguard file to build the sample-compose app on Windows (even if it crashes at launch)?

**Comment by PMARZV** [comment]
just a proguard file with -ignorewarnings. if not it was not even working exactly

**Comment by vinceglb** [comment]
Thanks for your help, I'm now able to reproduce when using proguard and `obfuscate.set(true)`.

I've been trying for 3 hours, but I don't find any solution for now... I have no idea what's going on here. I'll probably try later

**Comment by PMARZV** [comment]
i think adding this rules fixes it 
```
# JNA classes
-keep class com.sun.jna.** { *; }
-keepclassmembers class * extends com.sun.jna.** { public *; }
-keep class * implements com.sun.jna.** { *; }
-dontnote com.sun.**
``` 
But it basically tells proguard not to touch this class

**Comment by vinceglb** [comment]
@PMARZV I made a refactor recently of the whole Windows part and I took the occasion to understand why FileKit was not working by activating proguard and `obfuscate.set(true)`.

I realize that an annotation `@Structure.FieldOrder()` is not working like expected. I'm not sure if it's because FileKit uses Kotlin and the annotation only works with Java, or another problem? 

But I was able to fix the problem finally! 🎉

Now, we need to add those 2 lines to the proguard file and now everything is working fine with FileKit 0.8.0.

```
-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.** { *; }
```

Bonus: I refactored the whole Windows part to use the latest Windows API to display dialogs. Dialogs UI on Windows are now consistent (file picker, folder picker and save file dialogs).
